### PR TITLE
Added Multithreading

### PR DESCRIPTION
**Pull request by steveharwell1**

### CODE REVIEW

**Comment by nix-py** [comment]
For loop stops after one iteration. Please fix this.

**Comment by nix-py** [comment]
What is the purpose of using collections.Counter? I don't understand. Help me.

**Comment by nix-py** [comment]
Thnx for contributing. The idea is nice to concurrently download images. I'm waiting for your further commits.

**Comment by steveharwell1** [comment]
I will address the for loops this weekend. The Counter is used to take out any duplicate URLs before giving them to the threads. I didn't want to worry about a timing issue of two threads writing to the same file. If you know a better way of doing this I will incorporate that idea into my new commits this weekend.

**Comment by steveharwell1** [comment]
I don't see where the problem. My main loop assigns all urls for download. Can you help me replicate the issue? What is the command you passed and the output?

**Comment by nix-py** [comment]
The reason why for loop stops after one iteration is because you have `return` statement with in for loop, that causes it to return data only after one iteration, it should be outside of for loop.

If you try this one`./td.py qutoes -n 1000` it's only downloading first 50 images, though it should download all images from 1000 pages.

Now got my point?

**Comment by nix-py** [comment]
I'll try to understand how this multithreading works.

**Pull request closed without merging**
